config/routes.rb
get "milestones/total_graph", :to => "milestones#total_graph"
resources :projects do
  resources :milestones, :only => [:new, :create, :index]
end
resources :milestones, :only => [:show, :edit, :update, :destroy]

app/models/milestone.rb
class Milestone < ActiveRecord::Base

  belongs_to :user
  belongs_to :project
  has_many :milestone_versions, :dependent => :destroy
  has_many :versions, :through => :milestone_versions

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:project_id]
  validates_length_of :name, :maximum => 60
  validates :effective_date, :date => true, :allow_nil => true

  attr_accessible :name, :description, :effective_date

  def to_s
    name
  end

  def <=>(milestone)
    if self.effective_date
      milestone.effective_date ? (self.effective_date == milestone.effective_date ? self.name <=> milestone.name : self.effective_date <=> milestone.effective_date) : -1
    else
      milestone.effective_date ? 1 : (self.name <=> milestone.name)
    end
  end

  def versions?(version)
    versions.index(version) != nil
  end

  def completed?
    effective_date && (effective_date <= Date.today)
  end

end

app/models/milestone_version.rb
class MilestoneVersion < ActiveRecord::Base
  
  belongs_to :milestone
  belongs_to :version

end

app/controllers/milestones_controller.rb
require "advanced_roadmap/gruff/pie" if Object.const_defined?(:Magick)

class MilestonesController < ApplicationController
  menu_item :roadmap
  before_filter :find_project, :only => [:new, :create]
  before_filter :find_milestone, :only => [:show, :edit, :update, :destroy]
  before_filter :authorize, :except => [:show, :total_graph]

  helper :custom_fields
  helper :projects
  helper :versions
  include CustomFieldsHelper
  include ProjectsHelper

  def show
    projects = {}
    @milestone.versions.each do |version|
      version.fixed_issues.each do |issue|
        if !(projects.include?(issue.project.id))
          projects[issue.project.id] = issue.project.id
        end
      end
    end
    Version.sort_versions(@milestone.versions)
    @more_than_one_project = (projects.length > 1)
    @totals = Version.calculate_totals(@milestone.versions)
    @trackers = @project.trackers.sorted.all
    retrieve_selected_tracker_ids(@trackers, @trackers.select {|t| t.is_in_roadmap?})
  end

  def new
    @projects = Project.visible.order(:name).active
    @versions = @project.versions
    @milestone = Milestone.new
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def create
    @milestone = @project.milestones.build(params[:milestone])
    @milestone.user_id = User.current.id
    if request.post? and @milestone.save
      if params[:versions]
        params[:versions].each do |version|
          milestone_version = MilestoneVersion.new
          milestone_version.milestone_id = @milestone.id
          milestone_version.version_id = version
          milestone_version.save
        end
       end
      flash[:notice] = l(:notice_successful_create)
      redirect_to :controller => :projects, :action => :settings, :tab => "milestones", :id => @project
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def edit
    @projects = Project.order(:name).all
    @versions = @project.versions
  end

  def update
    @projects = Project.order(:name).all
    @versions = @project.versions
    versions_to_delete = @milestone.versions
    versions_to_add = []
    if params[:versions]
      params[:versions].each do |version|
        index = @milestone.versions.index(version)
        if index != nil
          versions_to_delete.remove(index)
        else
          versions_to_add << version
        end
      end
    end
    if @milestone.update_attributes(params[:milestone])
      versions_to_delete.each do |version|
        milestone_version = MilestoneVersion.where("milestone_id = #{@milestone.id} AND version_id = #{version.id}").first
        milestone_version.destroy
      end
      versions_to_add.each do |version|
        milestone_version = MilestoneVersion.new
        milestone_version.milestone_id = @milestone.id
        milestone_version.version_id = version
        milestone_version.save
      end
      flash[:notice] = l(:notice_successful_update)
      redirect_to :controller => :projects, :action => :settings, :tab => "milestones", :id => @project
    end
  end

  def destroy
    @milestone.destroy
    redirect_to :controller => :projects, :action => :settings, :tab => "milestones", :id => @project
  rescue
    flash[:error] = l(:notice_unable_delete_milestone)
    redirect_to :controller => :projects, :action => :settings, :tab => "milestones", :id => @project
  end

  def total_graph
    g = AdvancedRoadmap::Gruff::Pie.new(params[:size] || "500x400")
    g.hide_title = true
    g.theme = graph_theme
    g.margins = 0

    versions = params[:versions] || []
    percentajes = params[:percentajes] || []
    i = 0
    while i < versions.size and i < percentajes.size
      percentajes[i] = percentajes[i].to_f
      g.data(versions[i], percentajes[i])
      i += 1
    end

    headers["Content-Type"] = "image/png"
    send_data(g.to_blob, :type => "image/png", :disposition => "inline")
  end

private

  def find_project
    @project = Project.find(params[:project_id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_milestone
    @milestone = Milestone.find(params[:id])
    @project = @milestone.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def graph_theme
    {
      :colors => ["#DB2626", "#6A6ADB", "#64D564", "#F727F7", "#EBEB20", "#303030", "#12ABAD", "#808080", "#B7580B", "#316211"],
      :marker_color => "#AAAAAA",
      :background_colors => ["#FFFFFF", "#FFFFFF"]
    }
  end

  def retrieve_selected_tracker_ids(selectable_trackers, default_trackers=nil)
    if ids = params[:tracker_ids]
      @selected_tracker_ids = (ids.is_a? Array) ? ids.collect { |id| id.to_i.to_s } : ids.split('/').collect { |id| id.to_i.to_s }
    else
      @selected_tracker_ids = (default_trackers || selectable_trackers).collect {|t| t.id.to_s }
    end
  end

end

app/views/hooks/_milestones.html.erb
<%- if !@project.nil? -%>
<h3><%= l(:label_milestone_plural) %></h3>
<%- @project.milestones.sort.each do |milestone| -%>
<%= link_to_milestone(milestone) %><br />
<%- end -%>
<%- end -%>

app/views/hooks/_stylesheet.html.erb
<%= stylesheet_link_tag("advanced_roadmap", :plugin => "advanced_roadmap_v2", :media => "all") %>

app/views/hooks/calendars/_milestones.html.erb
<script language="javascript">
  function AddMilestoneToDay(milestoneName, milestoneUrl, day)
  {
    var cellElement = null;
    var dayOneFound = false;
    var elements = document.getElementsByTagName("*");
    for (var i = 0; (cellElement == null) && (i < elements.length); i++)
    {
      if (elements[i].className == "day-num")
      {
        var oneDay = parseInt(elements[i].childNodes[0].nodeValue);
        if ((!dayOneFound) && (oneDay == 1))
        {
          dayOneFound = true;
        }
        if (dayOneFound && (oneDay == day))
        {
          cellElement = elements[i].parentNode;
        }
      }
    }
    if (cellElement != null)
    {
      var link = document.createElement("a");
      link.innerHTML = milestoneName;
      link.href = milestoneUrl;
      var milestone = document.createElement("span");
      milestone.className = "icon icon-milestone calendar-milestone";
      milestone.appendChild(link);
      cellElement.appendChild(milestone);
    }
  }
  <%- if ((!(milestones.nil?)) and (milestones.any?)) -%>
    <%- milestones.each do |milestone| -%>
      AddMilestoneToDay("<%= milestone[:name] %>",
                        "<%= milestone[:url] %>",
                        <%= milestone[:day] %>);
    <%- end -%>
  <%- end -%>
</script>

app/views/hooks/issues/_show.html.erb
<tr>
    <%- milestones = @issue.fixed_version ? @issue.fixed_version.milestones.sort : []
        milestones = milestones.collect {|m| link_to(m.name, {:controller => :milestones, :action => :show, :id => m.id})}.join(", ").html_safe -%>
    <th class="fixed-version"><%=l(:label_milestone_plural)%>:</th>
    <td class="fixed-version"><%= milestones %></td>
    <%- if @issue.rest_hours > 0 &&
           User.current.allowed_to?(:view_time_entries, @project) and
           User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
      <th class="estimated-hours"><%=l(:label_roadmap_due_in, "")%>:</th>
      <td><%= l_hours(@issue.rest_hours) %></td>
    <%- end -%>
</tr>

app/views/milestones/_form.html.erb
<%= error_messages_for 'milestone' %>

<div class="box">
  <p><%= f.text_field :name, :size => 60, :required => true %></p>
  <p><%= f.text_field :description, :size => 60 %></p>
  <p><%= f.text_field :effective_date, :size => 10 %><%= calendar_for('milestone_effective_date') %></p>
  <p>
    <select id="project_selector" onchange="project_changed()">
      <% @projects.each do |project| %>
        <option<%= (project == @project) ? " selected" : "" %> id="<%= project.id %>"><%= h(project.name) %></option>
      <% end %>
    </select>
    <script>
      function project_changed()
      {
        object = window.document.getElementById("project_selector");
        if (object)
        {
          if (object.selectedIndex != -1)
          {
            project_id = object.options[object.selectedIndex].id;
            <% @projects.each do |project| %>
              project_div = window.document.getElementById("project_<%= project.id %>_versions");
              if (project_div)
              {
                project_div.style.display = "none";
                project_div.style.visibility = "hidden";
              }
            <% end %>
            project_div = window.document.getElementById("project_" + project_id + "_versions");
            if (project_div)
            {
              project_div.style.display = "";
              project_div.style.visibility = "";
            }
          }
        }
      }
      </script>
  </p>
  <% @projects.each do |project| %>
    <div id="project_<%= project.id %>_versions" style="<%= (@project == project) ? '' : 'display: none; visibility: hidden;' %>">
      <table class="list">
        <thead>
          <th><%= l(:field_version) %></th>
          <th><%= l(:field_effective_date) %></th>
          <th><%= l(:field_description) %></th>
          <th><%= l(:label_milestone_plural) %></th>
        </thead>
        <% project.versions.sort.each do |version| %>
          <tr class="<%= cycle("odd", "even") %>">
            <td>
              <%= check_box_tag "versions[]", version.id, @milestone.versions?(version) %>
              <%= link_to(h(version.name), :controller => :versions, :action => :show, :id => version) %>
            </td>
            <td align="center"><%= version.effective_date %></td>
            <td><%= version.description %></td>
            <td align="center"><%= version.milestones.collect {|m| link_to(h(m.name), :controller => :milestones, :action => :show, :id => m.id) }.join(", ").html_safe %></td>
          <tr>
        <% end %>
      </table>
    </div>
  <% end %>
</div>

app/views/milestones/edit.html.erb
<h2><%=l(:label_milestone)%></h2>

<%= labelled_form_for(@milestone) do |f| %>
  <%= render(:partial => "form", :locals => {:f => f}) %>
  <%= submit_tag(l(:button_save)) %>
<% end %>

app/views/milestones/new.html.erb
<h2><%=l(:label_milestone_new)%></h2>

<%= labelled_form_for([@project, @milestone]) do |f| %>
  <%= render(:partial => "form", :locals => {:f => f}) %>
  <%= submit_tag(l(:button_create)) %>
<% end %>

app/views/milestones/show.html.erb
<div class="contextual">
<%= link_to_if_authorized l(:button_edit), {:controller => :milestones, :action => :edit, :id => @milestone.id}, :class => 'icon icon-edit' %>
</div>

<h2><%= h(@milestone.name) %></h2>

<% if @milestone.completed? %>
  <p><%= format_date(@milestone.effective_date) %></p>
<% elsif @milestone.effective_date %>
  <p><strong><%= due_date_distance_in_words(@milestone.effective_date) %></strong> (<%= format_date(@milestone.effective_date) %>)</p>
<% end %>

<p><%= h(@milestone.description) %></p>

<% if @milestone.versions.empty? %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
<div id="roadmap">
<%= render(:partial => "versions/total", :locals => {:project => @project, :totals => @totals, :versions => @milestone.versions}) %>
<% @milestone.versions.each do |version| %>
    <h3 class="version"><%= tag 'a', :name => version.name %><%= link_to_version version %></h3>
    <%= render :partial => 'versions/info', :locals => {:version => version, :issues => version.sorted_fixed_issues(:trackers => @selected_tracker_ids), :totals => @totals} %>
    <%= call_hook :view_projects_roadmap_version_bottom, :version => version %>
<% end %>
</div>
<% end %>

<% content_for :sidebar do %>
<%= form_tag({}, :method => :get) do %>
<h3><%= l(:label_roadmap) %></h3>
<% @trackers.each do |tracker| %>
  <label><%= check_box_tag "tracker_ids[]", tracker.id, (@selected_tracker_ids.include? tracker.id.to_s), :id => nil %>
  <%=h tracker.name %></label><br />
<% end %>
<br />
<p><%= submit_tag l(:button_apply), :class => 'button-small', :name => nil %></p>
<% end %>

<h3><%= l(:label_milestone_plural) %></h3>
<% @milestone.project.milestones.sort.each do |milestone| %>
<%= link_to milestone.name, :controller => :milestones, :action => :show, :id => milestone.id %><br />
<% end %>
<h3><%= l(:label_version_plural) %></h3>
<%= link_to(l(:label_total), "##{l(:label_total)}") %><br />
<% @milestone.versions.each do |version| %>
<%= link_to format_version_name(version), "##{version.name}" %><br />
<% end %>
<% end %>

<% html_title(l(:label_roadmap)) %>

<%- if Redmine::VERSION::STRING < '3.4.0' -%>
  <%= context_menu issues_context_menu_path %>
<%- else -%>
  <%= context_menu %>
<%- end -%>

app/views/projects/settings/_milestones.html.erb
<% if @project.milestones.any? %>
<table class="list">
  <thead>
    <th><%= l(:label_milestone) %></th>
    <th><%= l(:field_effective_date) %></th>
    <th><%= l(:field_description) %></th>
    <th><%= l(:label_version_plural) %></th>
    <th style="width:15%"></th>
    <th style="width:15%"></th>
  </thead>
  <tbody>
  <% for milestone in @project.milestones.sort %>
    <tr class="<%= cycle 'odd', 'even' %>">
      <td><%= link_to h(milestone.name), :controller => :milestones, :action => :show, :id => milestone.id %></td>
      <td align="center"><%= format_date(milestone.effective_date) %></td>
      <td><%=h milestone.description %></td>
      <td align="center"><%= milestone.versions.sort { |a, b| a.name.downcase <=> b.name.downcase }.collect {|v| link_to(h(v.name), :controller => :versions, :action => :show, :id => v) }.join(", ").html_safe %></td>
      <td align="center"><%= link_to_if_authorized l(:button_edit), { :controller => :milestones, :action => :edit, :id => milestone.id }, :class => 'icon icon-edit' %></td>
      <td align="center"><%= link_to_if_authorized l(:button_delete), {:controller => :milestones, :action => :destroy, :id => milestone.id }, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %></td>
    </tr>
  <% end; reset_cycle %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to l(:label_milestone_new), new_project_milestone_path(@project, :back_url => ''), :class => 'icon icon-add' if User.current.allowed_to?(:manage_milestones, @project) %></p>

app/views/settings/_advanced_roadmap_settings.html.erb
<%- defaults = Redmine::Plugin::registered_plugins[:advanced_roadmap_v2].settings[:default] -%>

<p>
  <%= label_tag 'settings[show_due_time]', l(:label_setting_show_due_time) %>
  <%= check_box_tag('settings[show_due_time]', 'true', @settings["show_due_time"]) %>
</p>

<p>
  <%= label_tag 'settings[solved_issues_to_estimate]', l(:label_setting_solved_issues_to_estimate) %>
  <%= text_field_tag('settings[solved_issues_to_estimate]', @settings["solved_issues_to_estimate"] || defaults["solved_issues_to_estimate"]) %>
</p>

<p>
  <%= label_tag 'settings[ratio_good]', l(:label_setting_ratio_good) %>
  <%= text_field_tag('settings[ratio_good]', @settings["ratio_good"] || defaults["ratio_good"]) %>
</p>

<p>
  <%= label_tag 'settings[color_good]', l(:label_setting_color_good) %>
  <%= text_field_tag('settings[color_good]', @settings["color_good"] || defaults["color_good"]) %>
</p>

<p>
  <%= label_tag 'settings[ratio_bad]', l(:label_setting_ratio_bad) %>
  <%= text_field_tag('settings[ratio_bad]', @settings["ratio_bad"] || defaults["ratio_bad"]) %>
</p>

<p>
  <%= label_tag 'settings[color_bad]', l(:label_setting_color_bad) %>
  <%= text_field_tag('settings[color_bad]', @settings["color_bad"] || defaults["color_bad"]) %>
</p>

<p>
  <%= label_tag 'settings[ratio_very_bad]', l(:label_setting_ratio_very_bad) %>
  <%= text_field_tag('settings[ratio_very_bad]', @settings["ratio_very_bad"] || defaults["ratio_very_bad"]) %>
</p>

<p>
  <%= label_tag 'settings[color_very_bad]', l(:label_setting_color_very_bad) %>
  <%= text_field_tag('settings[color_very_bad]', @settings["color_very_bad"] || defaults["color_very_bad"]) %>
</p>

app/views/versions/_info.html.erb
<%= render :partial => 'versions/overview', :locals => {:version => version} %>
<%= render(:partial => "wiki/content", :locals => {:content => version.wiki_page.content}) if version.wiki_page %>

<%- # Version cached values.
    version_estimated_speed = version.estimated_speed
    version_spent_hours = version.spent_hours
    version_rest_hours = version.rest_hours
    version_speed_rest_hours = version.speed_rest_hours
    version_parallel_rest_hours = version.parallel_rest_hours
    version_parallel_speed_rest_hours = version.parallel_speed_rest_hours -%>

<%- if (params[:controller] == "versions" and params[:action] == "index") or
       (params[:controller] == "milestones" and params[:action] == "show") -%>
  <table>
    <%- if (totals[:spent_hours] + totals[:rest_hours]) > 0 -%>
      <tr>
        <td width="310px" align="right">% <%= (params[:controller] == "milestones") ? l(:label_milestone) : l(:label_project) %></td>
        <td width="340px" class="total-hours"><%= "%.0f" % (((version_spent_hours + version_rest_hours) * 100.0) / (totals[:spent_hours] + totals[:rest_hours])) %>%</td>
      </tr>
    <%- end -%>
    <%- if User.current.allowed_to?(:view_time_entries, @project) and
           User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
      <%- if !version_estimated_speed.nil? -%>
        <tr>
            <td width="310px" align="right">% <%= l(:label_estimated_speed) %></td>
            <td width="340px" class="total-hours"><font color="<%= color_by_ratio(version_estimated_speed) %>"><%= ("%.0f" % (100.0 / version_estimated_speed)) %>%</font></td>
        </tr>
      <%- end -%>
      <%- if version_rest_hours > 0.0 %>
        <tr>
          <td width="310px" align="right"><%= l(:label_roadmap_due_in, "") %></td>
            <%- due, tmp = '', version_rest_hours 
                due << l_weeks(tmp.div 40) << ' ' and tmp %= 40.0 if (tmp / 40.0) > 1.0
                due << l_days(tmp.div 8) << ' ' and tmp %= 8.0 if (tmp / 8.0) > 1.0
                due << l_hours(tmp) if tmp > 0.0 %>
          <td width="340px" class="total-hours"><%= "#{due}" %></td>
        </tr>
        <%- if version_rest_hours != version_speed_rest_hours -%>
          <tr>
            <td width="310px" align="right"><%= l(:label_roadmap_due_in, "") %> (<%= l(:label_estimated_speed) %>)</td>
            <%- due = l_hours(version_speed_rest_hours) %>
            <%- due = l_days(version_speed_rest_hours / 8.0) if (version_speed_rest_hours / 8.0) > 1.5 %>
            <%- due = l_weeks(version_speed_rest_hours / 40.0) if (version_speed_rest_hours / 40.0) > 1.5 %>
            <td width="340px" class="total-hours"><%= "#{due}" %></td>
          </tr>
        <%- end -%>
      <%- end -%>
    <%- end -%>
  </table>
<%- end -%>

<%- if issues.present? -%>
<%- show_due_time = (Setting.plugin_advanced_roadmap_v2["show_due_time"]) -%>
<fieldset class="related-issues"><legend><%= l(:label_related_issues) %></legend>
<%= form_tag({}) do %>
<table class="list related-issues">
  <thead>
   <tr class="related-issues-header">
    <%- width = 73
        if User.current.allowed_to?(:view_issue_estimated_hours, @project)
          width -= 9 # estimated hours
        end
        if User.current.allowed_to?(:view_time_entries, @project)
          width -= 9 # spent time
          if User.current.allowed_to?(:view_issue_estimated_hours, @project)
            width -= 9 # due in
            if !version_estimated_speed.nil?
              width -= 9 # estimated speed
            end
          end
        end -%>
    <% nb_of_issues_with_category = issues.count{|i| !i.category.blank? } %>
    <% if nb_of_issues_with_category > 0 %>
      <th width="14%" align="left"><%= l(:field_category) %></th>
    <% end %>
    <th width="#{width}%" align="left"><%= l(:field_issue) %></th>
    <%- if User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
      <th width="9%" align="center"><%= l(:field_estimated_hours) %></th>
    <%- end -%>
    <%- if User.current.allowed_to?(:view_time_entries, @project) -%>
      <th width="9%" align="center"><%= l(:label_spent_time) %></th>
    <%- end -%>
    <th width="9%" align="center"><%= l(:field_done_ratio) %></th>
    <%- if User.current.allowed_to?(:view_time_entries, @project) and
           User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
      <th width="9%" align="center">
         <%= ( show_due_time ? l(:label_roadmap_due_in, "") : l(:field_due_date) ) %>  
      </th>
      <%- if !version_estimated_speed.nil? -%>
        <th width="9%" align="center"><%= l(:label_roadmap_due_in, "") %><br />(<%= l(:label_estimated_speed) %>)</th>
      <%- end -%>
    <%- end -%>
   </tr>
  </thead>
  <tbody>
  <%- issues.each do |issue| -%>
    <%- # Issue cached values.
        issue_estimated_hours = issue.estimated_hours
        issue_spent_hours = issue.total_spent_hours
        issue_done_ratio = issue.done_ratio
        issue_rest_hours = issue.rest_hours

        color = ""
        begin_strike = ""
        end_strike = ""
        if issue_estimated_hours && issue_done_ratio
          color = color_by_ratio(issue_spent_hours / ((issue_estimated_hours * issue_done_ratio) / 100.0))
        end
        if issue.closed?
          begin_strike = "<strike>".html_safe
          end_strike = "</strike>".html_safe
        end -%>
    <tr class="hascontextmenu <%= cycle("odd", "even") %>">
      <%- tab = ("&nbsp;" * 3 * issue.parents_count).html_safe -%>
      <% if nb_of_issues_with_category > 0 %>
        <td style="text-align: left;"><%= issue.category %></td>
      <% end %>
      <td class="checkbox" align="left"><%= check_box_tag("ids[]", issue.id) %></td>
      <td align="left" style="text-align: left;">
        <div class="advanced-roadmap tooltip">
          <%= tab %>
          <font color="<%= color %>"><%= begin_strike %>
            <%= link_to_issue(issue, :project => (@project != issue.project)) %>
          <%= end_strike %></font>
          <span class="tip">
            <table width="100%">
              <tr><td colspan="2"><%= link_to_issue(issue) %></td></tr>
              <%- if @project != issue.project -%>
              <tr><td><strong><%= l(:field_project) %>:</strong></td><td><%= link_to_project(issue.project) %></td></tr>
              <%- end -%>
              <tr><td><strong><%= l(:field_status) %>:</strong></td><td><%= issue.status.name %></td></tr>
              <tr><td><strong><%= l(:field_priority) %>:</strong></td><td><%= issue.priority.name %></td></tr>
              <tr><td><strong><%= l(:field_assigned_to) %>:</strong></td><td><%= link_to_user(issue.assigned_to) %></td></tr>
              <tr><td><strong><%= l(:field_category) %>:</strong></td><td><%= issue.category %></td></tr>
              <tr><td><strong><%= l(:field_start_date) %>:</strong></td><td><%= format_date(issue.start_date) %></td></tr>
              <tr><td width="40%"><strong><%= l(:field_due_date) %>:</strong></td><td width="60%"><%= format_date(issue.due_date) %></td></tr>
            </table>
          </span>
        </div>
      </td>
      <%- if User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
        <td align="center"><font color="<%= color %>"><%= begin_strike %><%= ("%.2f" % issue_estimated_hours) if issue_estimated_hours %><%= end_strike %></font></td>
      <%- end -%>
      <%- if User.current.allowed_to?(:view_time_entries, @project) -%>
        <td align="center"><font color="<%= color %>"><%= begin_strike %><%= "%.2f" % issue_spent_hours %><%= end_strike %></font></td>
      <%- end -%>
      <td align="center"><font color="<%= color %>"><%= begin_strike %><%= (("%.0f" % issue_done_ratio) + "%") %><%= end_strike %></font></td>
      <%- if User.current.allowed_to?(:view_time_entries, @project) and
             User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
        <td align="center"><font color="<%= color %>">
          <%- if show_due_time -%>
            <%= begin_strike %><%= ("%.2f" % issue_rest_hours) if issue_estimated_hours or issue_spent_hours %><%= end_strike %>
          <%- else -%>
            <%= format_date(issue.due_date) %>
          <%- end -%>
        </font></td>
        <%- if !version_estimated_speed.nil? -%>
          <td align="center"><font color="<%= color %>"><%= begin_strike %><%= ("%.2f" % (issue_rest_hours * ((!issue.closed? and (!issue_spent_hours or issue_spent_hours <= 0.0) and !version_estimated_speed.nil?) ? version_estimated_speed : 1.0))) if issue_estimated_hours or issue_spent_hours %><%= end_strike %></font></td>
        <%- end -%>
      <%- end -%>
    </tr>
  <%- end -%>
  </tbody>
  <thead>
   <tr class="related-issues-footer">
    <th align="left"><%= l(:label_total) %></th>
    <%- if nb_of_issues_with_category > 0 %>
      <th></th>
    <%- end %>
    <%- if User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
      <th align="center"><%= ("%.2f" % version.estimated_hours) %></th>
    <%- end -%>
    <%- if User.current.allowed_to?(:view_time_entries, @project) -%>
      <th align="center"><%= ("%.2f" % version_spent_hours) %></th>
    <%- end -%>
    <th align="center"><%= ("%.0f" % version.completed_percent) %>%</th>
    <%- if User.current.allowed_to?(:view_time_entries, @project) and
           User.current.allowed_to?(:view_issue_estimated_hours, @project) -%>
      <th align="center">
       <%- if show_due_time -%>
         <%= ("%.2f" % version_rest_hours) %>
       <%- else -%>
         <%= format_date(version.due_date) %>
       <%- end -%>
      </th>
      <%- if !version_estimated_speed.nil? -%>
        <th align="center"><%= ("%.2f" % version_speed_rest_hours) %></th>
      <%- end -%>
    <%- end -%>
   </tr>
  </thead>
</table>
<% end %>
</fieldset>
<%- end -%>